---

- name: update repo and install ruby
  hosts: all
  become: true
  tasks:
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: present
  vars:
    packages:
    - ruby-full
    - ruby-bundler
    - build-essential


